Dev
Oljk/express_proj pull request #1
Opened 2021-01-04 23:06 UTC by Oljk

dz 3-14 December

2021-01-11 21:02 UTC, ddavidov requested changes

2021-01-11 21:02 UTC, ddavidov commented on .env
> +HOST=localhost
Не, этот файл нужно заигнорить в .gitignore

2021-01-11 21:02 UTC, ddavidov commented on api/myconf.js
> +    get Port() {
Рекомендую подумать, как можно универсализировать getter'ы в этом классе. Хочу видеть универсальный метод типа `getVar(varName, defaultvalue = null) { ... }`. Если я где-то его в коде вызову, например как ```config.getVar('PORT'); ``` или ```config.getVar('port');``` или ещё вариант - статический метод типа ```MyConf.getVar('port');``` то получу то, что задано в `process.env.PORT`. Сможете реализовать - будет супер.

2021-01-18 22:30 UTC, Oljk commented on api/myconf.js
> +    get Port() {
changed in https://github.com/Oljk/express_proj/pull/1/commits/8b35e09084f1ae9e6e02f1ebac6a365a0099d124

2021-01-21 22:17 UTC, merged